name: Preview site for PRs

on:
  pull_request:
    types: [opened, reopened, synchronize, closed]
  workflow_dispatch:

concurrency:
  group: preview-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write # required to push preview files to gh-pages
  pull-requests: write
  pages: read

jobs:
  build-and-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Setup Node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f
        with:
          node-version-file: .nvmrc
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - name: SLSA action
        uses: ministryofjustice/devsecops-actions/sca/slsa@9ec6779d39e07ca69ecf17baf5208a4b0095c10b
      - name: Install deps
        if: github.event.action != 'closed'
        run: npm ci

      - name: Build preview
        if: github.event.action != 'closed'
        run: npm run build
        env:
          PATHPREFIX: /pr-preview/pr-${{ github.event.pull_request.number }}/

      - name: Deploy PR preview
        uses: rossjrw/pr-preview-action@ffa7509e91a3ec8dfc2e5536c4d5c1acdf7a6de9
        with:
          source-dir: _site
          preview-branch: gh-pages
          umbrella-dir: pr-preview
          action: auto
